<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ShaderCompiler>third_party\glslang\glslangValidator.exe</ShaderCompiler>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <ShaderCompiler>glslangValidator</ShaderCompiler>
  </PropertyGroup>

  <PropertyGroup>
    <CommonShaderArgs>--enhanced-msgs --nan-clamp -V -e main</CommonShaderArgs>
  </PropertyGroup>

  <ItemGroup>
    <Shader Include="src/*.glsl">
      <Name>$([System.Text.RegularExpressions.Regex]::Match(%(Identity), '((?:\w|\.|_)+)(?=\.(?:vs|fs|cs)\.glsl$)'))</Name>
      <Stage>$([System.Text.RegularExpressions.Regex]::Match(%(Identity), '(vs|fs|cs)(?=\.glsl$)'))</Stage>
      <InFile>%(Identity)</InFile>
      <OutFile Condition="%(Name) != '' And %(Stage) != ''">src/%(Name).%(Stage).spirv</OutFile>
      <CompileCommand Condition="%(Stage) == 'vs'">$(ShaderCompiler) $(CommonShaderArgs) -S vert -o %(OutFile) %(Identity)</CompileCommand>
      <CompileCommand Condition="%(Stage) == 'fs'">$(ShaderCompiler) $(CommonShaderArgs) -S frag -o %(OutFile) %(Identity)</CompileCommand>
      <CompileCommand Condition="%(Stage) == 'cs'">$(ShaderCompiler) $(CommonShaderArgs) -S comp -o %(OutFile) %(Identity)</CompileCommand>
    </Shader>
  </ItemGroup>

  <Target Name="CompileShaders" BeforeTargets="ResolveReferences"
          Inputs="@(Shader)"
          Outputs="%(Shader.OutFile)">
    <Message Importance="High" Text="--- compiling: %(Shader.InFile) -> %(Shader.OutFile)" />
    <Exec Command="%(Shader.CompileCommand)" />
    <ItemGroup>
      <EmbeddedResource Include="%(Shader.OutFile)" />
    </ItemGroup>
  </Target>

  <!--
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <ShaderCompiler>third_party\glslang\glslangValidator.exe</ShaderCompiler>
  </PropertyGroup>
  -->

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <CPlusPlusCompiler>clang++</CPlusPlusCompiler>
  </PropertyGroup>

  <PropertyGroup>
    <CPlusPlusCompilerArgs>-c -std=c++2c -Wc23-extensions</CPlusPlusCompilerArgs>
  </PropertyGroup>

  <PropertyGroup>
    <CPlusPlusLinkerArgs>-std=c++2c -lvulkan -lasound</CPlusPlusLinkerArgs>
  </PropertyGroup>

  <ItemGroup>
    <TranslationUnit Include="src/*.cpp">
      <Name>$([System.Text.RegularExpressions.Regex]::Match(%(Identity), '((?:\w|\.|_)+)(?=\.cpp)'))</Name>
      <InFile>%(Identity)</InFile>
      <OutFile Condition="%(Name) != ''">%(Name).o</OutFile>
      <CompileCommand>$(CPlusPlusCompiler) $(CPlusPlusCompilerArgs) -o %(OutFile) %(Identity)</CompileCommand>
    </TranslationUnit>
  </ItemGroup>

  <Target Name="CompileObjects" DependsOnTargets="CompileShaders" BeforeTargets="ResolveReferences"
          Inputs="@(TranslationUnit);@(Shader)"
          Outputs="%(TranslationUnit.OutFile)">
    <Message Importance="High" Text="--- compiling: %(TranslationUnit.InFile) -> %(TranslationUnit.OutFile)" />
    <Exec Command="%(TranslationUnit.CompileCommand)" />
  </Target>

  <Target Name="CompileLibrary" DependsOnTargets="CompileObjects" BeforeTargets="ResolveReferences"
          Inputs="@(TranslationUnit)"
          Outputs="convolver">
    <Message Importance="High" Text="--- linking: %(TranslationUnit.OutFile)" />
    <Exec Command="$(CPlusPlusCompiler) $(CPlusPlusLinkerArgs) *.o -o convolver" />
  </Target>


</Project>
